CREATE TABLE USERS (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  EMAIL VARCHAR(255) NOT NULL,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(255) NOT NULL,
  BIRTHDAY DATE NOT NULL,
  ADDRESS VARCHAR(255),
  PHONE_NUMBER VARCHAR(16)
);